Muhammad Arslan
Roll No 138.20

In [3]:
import numpy as np

Question 1: Import the NumPy library and create a NumPy array containing the integers from 1 to 10.
Print the array.

In [4]:
arr = np.arange(1,11)
print(arr)
print(type(arr))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


Question 2: Create a 3x3 NumPy array filled with zeros and print it

In [5]:
ar1 = np.zeros([3,3])
ar1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Question 3: Create two NumPy arrays of the same shape and perform element-wise addition on them

In [6]:
a = np.array([2,3,4,5,6])
b = np.array([1,4,6,8,0])
c = a+b
print(c)

[ 3  7 10 13  6]


Question 4: Create a NumPy array with values from 1 to 10 and calculate the mean, median, and standard
deviation of the values

In [7]:
arrr = np.arange(1,11)
mn = np.mean(arrr)
sd = np.std(arrr)
med = np.median(arrr)
print(f'mean is {mn}, standard deviation is {sd}, median is {med}')


mean is 5.5, standard deviation is 2.8722813232690143, median is 5.5


Question 5: Create a NumPy array containing the integers from 1 to 20. Slice it to print the even numbers
from the array.

In [8]:
ab = np.arange(1,21)
print(ab)
c = ab[ab%2==0]
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]


Question 6: Create a 2D NumPy array and print the last row and last column of the array.


In [9]:
ac = np.array([[2,3,4],[2,3,6],[4,5,7]])
print(ac)
lastRow = ac[-1,:]
lastColumn = ac[:,-1]
print(f'last row is {lastRow}, last Column is {lastColumn}')

[[2 3 4]
 [2 3 6]
 [4 5 7]]
last row is [4 5 7], last Column is [4 6 7]


Question 7: Create a NumPy array with random integers between 1 and 100. Find the maximum and
minimum values in the array.


In [10]:
ran = np.random.random((1,100))
minimum = ran.min()
minimum
maximum = ran.max()
maximum
print(f'Minimum value is{minimum}, Maximum Vales is {maximum}')

Minimum value is0.0037628410138526025, Maximum Vales is 0.9970413102570325


Question 8: Create a NumPy array and find the unique values in the array.

In [25]:
av = np.array([2,3,5,7,8,90,3])
c = np.unique(av)
print(c)

[ 2  3  5  7  8 90]


Question 9: Create two NumPy matrices and perform matrix multiplication on them

In [12]:
array1 = np.array([2,3,4,5,6])
array2 = np.array([4,5,6,7,8])
multiply = array1 * array2
print(multiply)

[ 8 15 24 35 48]


Question 10: Create a square NumPy matrix and calculate its determinant.

In [13]:
sq = np.array([[2,3],[3,5]])
det = np.linalg.det(sq)
print(f'determinant of square matrix is {det}')

determinant of square matrix is 0.9999999999999991


Question 11: Create a NumPy array and add a scalar to all its elements.


In [29]:
arr1 = np.array([1,2,3,5,7,9])
scalar = 3
result = scalar + arr1
print(result)

[ 4  5  6  8 10 12]


Question 12: Create a 2D NumPy array and add a 1D array to each row

In [15]:
a = np.array([1,2,3])
b = np.array([(5,2,3), (4,5,6)])
c = a+b
print(c)

[[6 4 6]
 [5 7 9]]


Question 13: Generate a NumPy array of random integers and calculate the mean, median, standard
deviation, and variance of the values.


In [16]:
ran = np.random.random((1,100))
mn = ran.mean()
med = np.median(ran)
sd = ran.std()
var = ran.var()
print(f'Random integers array mean is {mn}, median is {med}, standard devivation is {sd}, varinace is {var} ')


Random integers array mean is 0.4924738454898809, median is 0.4818845000072218, standard devivation is 0.28292579007949886, varinace is 0.08004700269210867 


Question 14: Create a NumPy array and find the 75th percentile and cumulative sum of the values.

In [17]:
arr = np.array([2,3,5,7,8,9])
per = np.percentile(arr,75)
per
comp = np.cumsum(arr)
comp
print(f'75th Percentile of array is {per}, and  cumulative sum of array is {comp}')

75th Percentile of array is 7.75, and  cumulative sum of array is [ 2  5 10 17 25 34]


Question 15: Create a NumPy array and find the absolute difference between each element and the mean
of the array.

In [18]:
arr = np.array([2,3,5,7,8,9])
mn = np.mean(arr)
diff = np.abs(arr - mn )
print(f'Mean of array is {mn},Absolute differnce is{diff}')

Mean of array is 5.666666666666667,Absolute differnce is[3.66666667 2.66666667 0.66666667 1.33333333 2.33333333 3.33333333]


Question 16: Generate a NumPy array of random numbers and find the mode of the values.

In [30]:
arr = np.array([2, 3, 2, 1, 5, 2, 6, 2, 7, 2])
unique_values, counts = np.unique(arr, return_counts=True)
mode_index = np.argmax(counts)
mode = unique_values[mode_index]
print(mode)


2


Question 17: Create a NumPy array and reshape it into a 3x4 matrix

In [28]:
az = np.array([1,2,3,2,4,6,8,0,9,4,2,4])
ac =az.reshape(3,4)
print(ac)

[[1 2 3 2]
 [4 6 8 0]
 [9 4 2 4]]


Question 18: Create a NumPy array and find the indices of the maximum and minimum values in the array.


In [21]:
arr = np.array([2,3,5,7,9,4,2,1,3,6,8,6,5])
min_index = np.argmin(arr)
max_index = np.argmax(arr)
print(f'Minimum value index is {min_index}, Maximum value index is {max_index}')

Minimum value index is 7, Maximum value index is 4


Question 19: Create a NumPy array and sort it in ascending order

In [27]:
af = np.array([1,2,3,2,4,6,8,0,9,4,2,4])
a =np.sort(af)
print(a)

[0 1 2 2 2 3 4 4 4 6 8 9]


Question 20: Create a NumPy array and find the unique values in the array.

In [26]:
aa = np.array([1,2,4,5,3,5,3,1,3,5,7,8,4,2,4,2])
c = np.unique(aa)
print(c)

[1 2 3 4 5 7 8]


Question 21: Create a NumPy array and find the unique values and their counts.

In [24]:
sa = np.array([1,2,4,5,3,5,3,1,3,5,7,8,4,2,4,2])
kk , count1 = np.unique(sa, return_counts=True)
print(kk)
print(count1)

[1 2 3 4 5 7 8]
[2 3 3 3 3 1 1]
